title: Cloud Security with VNetLady
description: Sharing interesting topics about cybersecurity and cloud security
theme: minima
  
#Optional
url: "https://laghim.github.io"
permalink: pretty
future: true

excerpt_separator: "<!--more-->"

