title: Cloud Security with VNetLady
description: >
    Sharing interesting topics about cybersecurity and cloud security
theme: minima
  
#Optional
url: "https://laghim.github.io"
permalink: pretty
future: true

excerpt_separator: "<!--more-->"

author:
    name: "Laura Ghimpeteanu"

social_links:
    title: Find me on GitHub
    icon: github
    url: "https://github.com/laghim"
    title: Find me on LinkedIn
    icon: linkedin
    url: "https://linkedin.com/laghim"
    
hide_site_feed_link: true

