title: Cloud Security with VNetLady
description: >
    Security Cloud Solution Architect at Microsoft.Sharing interesting topics about cybersecurity and cloud security
theme: minima
  
#Optional
url: "https://laghim.github.io"
permalink: pretty
future: true

excerpt_separator: "<!--more-->"

author: "Laura Ghimpeteanu"

minima:
  social_links:
    - title: "Minima Theme repository at GitHub"
      icon: "github"
      url: "https://github.com/jekyll/minima"
    - title: "Jekyll at X (formerly Twitter)"
      icon: "x-twitter"
      url: "https://x.com/jekyllrb"
  hide_site_feed_link: true

show_excerpts: true

nav_pages:
  - about.md

