title: Cloud Security with VNetLady
description: >
    Security Cloud Solution Architect at Microsoft.Sharing interesting topics about cybersecurity and cloud security
theme: minima
  
#Optional
url: "https://laghim.github.io"
permalink: pretty
future: true

excerpt_separator: "<!--more-->"

author: "Laura Ghimpeteanu"
linkedin: "https://linkedin.com/in/laghim"

show_excerpts: true

nav_pages:
  - about.md

